export const LEGACY_API_METHODS = Object.freeze([
  'getPayrollBootstrapData',
  'getTuitionBootstrapData',
  'getTuitionMonthSummary',
  'getTuitionStudentMonthlyHistory',
  'getTuitionStudentMemoNotes',
  'getTuitionGuideDashboard',
  'getTuitionMonthlySalesOverview',
  'backfillTuitionMonthSnapshots',
  'backfillTuitionPaymentsToFirestore',
  'backfillTuitionFollowupsToFirestore',
  'backfillTuitionMonthChargesToFirestore',
  'completeTuitionFirestoreMigration',
  'saveTuitionStatusOnly',
  'saveTuitionFollowup',
  'saveTuitionStudentMemo',
  'saveTuitionAmountAdjustment',
  'appendTuitionPaymentEntry',
  'deleteTuitionPaymentEntry',
  'getDeskScheduleMonthData',
  'getDeskCalendarEvents',
  'saveDeskScheduleEntry',
  'batchUpdateDeskScheduleEntries',
  'deleteDeskScheduleEntry',
  'getDeskDailyJournalData',
  'getDeskDailyJournalPendingTasks',
  'saveDeskDailyJournalTask',
  'deleteDeskDailyJournalTask',
  'saveDeskDailyJournalMemo',
  'deleteDeskDailyJournalMemo',
  'getDeskSuppliesData',
  'adjustDeskSupplyConsumable',
  'saveDeskSupplyConsumable',
  'deleteDeskSupplyConsumable',
  'saveDeskSupplyAsset',
  'deleteDeskSupplyAsset',
  'saveDeskSupplyPurchaseState',
  'getDeskRecruitingApplicantsData',
  'saveDeskRecruitingApplicant',
  'deleteDeskRecruitingApplicant',
  'getPayrollMonthSummary',
  'getPayrollSettings',
  'savePayrollSettings',
  'savePayrollOverrides'
]);

export const MIGRATION_STATE = Object.freeze({
  phase: 5,
  legacyMethods: LEGACY_API_METHODS.length,
  migratedBusinessMethods: 42,
  migratedDomains: Object.freeze(['schedule', 'dailyJournal', 'supplies', 'recruiting', 'tuition', 'payroll', 'googleWorkspace']),
  maintenanceOnlyLegacyMethods: Object.freeze([
    'backfillTuitionMonthSnapshots',
    'backfillTuitionPaymentsToFirestore',
    'backfillTuitionFollowupsToFirestore',
    'backfillTuitionMonthChargesToFirestore',
    'completeTuitionFirestoreMigration'
  ]),
  productionTrafficSwitched: true
});
